# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA OpenDNS Updater
version: "1.1.2"
slug: example
description: HA OpenDNS Updater Add-on
url: "https://github.com/Frazou1/haopendnsupdater"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
boot: "auto"
options:
  username: "votre_utilisateur_opendns"
  password: "votre_mot_de_passe_opendns"
  network_label: "votre_label_reseau"
  check_interval: 300
schema:
  username: "str"
  password: "str"
  network_label: "str"
  check_interval: "int"
build:
  builder: docker
  file: Dockerfile
