# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "HA OpenDNS Updater"
version: "1.1.5"
slug: "haopendnsupdater"
description: "HA OpenDNS Updater Add-on"
url: "https://github.com/Frazou1/haopendnsupdater"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
boot: "auto"
options:
  username: "votre_utilisateur_opendns"
  password: "votre_mot_de_passe_opendns"
  network_label: "votre_label_reseau"
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_username: "votre_utilisateur_mqtt"
  mqtt_password: "votre_mot_de_passe_mqtt"
  check_interval: 300
schema:
  username: str
  password: str
  network_label: str
  check_interval: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
build:
  builder: docker
  file: Dockerfile
